// Generated by: supabase gen types typescript --project-id <your-project-id>
// Run this command after schema is deployed and replace this file's contents.
// Until generated, use this placeholder to allow TypeScript compilation.
export type Database = {
  public: {
    Tables: {
      clients: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      leads: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      calls: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      sms_sequences: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      billing: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
      client_users: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown> }
    }
  }
}
